version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: crude-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: CrudeDB
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - crude-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  crude-network:
    driver: bridge